import cx_Freeze
from cx_Freeze import *

build_msi_options = {
    'packages': ['pygame', 'time', 'random', 'sys', 'csv'],

    'include_files': [  
        'arrow_yellow_down.png',
        'arrow_yellow_up.png',
        'boss.png',
        'boss_2.png',
        'boss_3.png',
        'boss_4.png',
        'boss_damage.wav',
        'boss_down.png',
        'boss_sound.wav',
        'bull.png',
        'bull_2.png',
        'bull_3.png',
        'cof.png',
        'coffee.wav',
        'cof_2.png',
        'cup.png',
        'cup.wav',
        'dead.png',
        'game_over.wav',
        'ground.png',
        'ground2.png',
        'ground3.png',
        'ground_2.png',
        'heart.png',
        'heart_2.png',
        'hurt.png',
        'hurt.wav',
        'intro_wall.png',
        'intro_wall_2.png',
        'key.png',
        'key.wav',
        'key_2.png',
        'key_3.png',
        'maps.png',
        'maze_1.png',
        'maze_10.png',
        'maze_11.png',
        'maze_12.png',
        'maze_13.1.png',
        'maze_13.2.png',
        'maze_14.png',
        'maze_15.png',
        'maze_2.png',
        'maze_3.png',
        'maze_4.png',
        'maze_5.png',
        'maze_6.png',
        'maze_7.png',
        'maze_8.png',
        'maze_9.png',
        'runa.png',
        'score.csv',
        'shadow.png',
        'slime.png',
        'slime_2.png',
        'slime_3.png',
        'slime_4.png',
        'start.wav',
        'start_1.png',
        'start_2.png',
        'theme_1.wav',
        'theme_2.wav',
        'trophy.png',
        'uni_hit_box.png',
        'uni_left.png',
        'uni_right.png',
        'view.png',
        'wolf.png',
        'wolf_2.png',
        'wolf_3.png',
        'wolf_4.png',
        'icon.ico'
    ],
}

build_exe_options = {
    'packages': ['pygame', 'time', 'random', 'sys', 'csv'],

    'include_files': [  
        'arrow_yellow_down.png',
        'arrow_yellow_up.png',
        'boss.png',
        'boss_2.png',
        'boss_3.png',
        'boss_4.png',
        'boss_damage.wav',
        'boss_down.png',
        'boss_sound.wav',
        'bull.png',
        'bull_2.png',
        'bull_3.png',
        'cof.png',
        'coffee.wav',
        'cof_2.png',
        'cup.png',
        'cup.wav',
        'dead.png',
        'game_over.wav',
        'ground.png',
        'ground2.png',
        'ground3.png',
        'ground_2.png',
        'heart.png',
        'heart_2.png',
        'hurt.png',
        'hurt.wav',
        'intro_wall.png',
        'intro_wall_2.png',
        'key.png',
        'key.wav',
        'key_2.png',
        'key_3.png',
        'maps.png',
        'maze_1.png',
        'maze_10.png',
        'maze_11.png',
        'maze_12.png',
        'maze_13.1.png',
        'maze_13.2.png',
        'maze_14.png',
        'maze_15.png',
        'maze_2.png',
        'maze_3.png',
        'maze_4.png',
        'maze_5.png',
        'maze_6.png',
        'maze_7.png',
        'maze_8.png',
        'maze_9.png',
        'runa.png',
        'score.csv',
        'shadow.png',
        'slime.png',
        'slime_2.png',
        'slime_3.png',
        'slime_4.png',
        'start.wav',
        'start_1.png',
        'start_2.png',
        'theme_1.wav',
        'theme_2.wav',
        'trophy.png',
        'uni_hit_box.png',
        'uni_left.png',
        'uni_right.png',
        'view.png',
        'wolf.png',
        'wolf_2.png',
        'wolf_3.png',
        'wolf_4.png',
        'icon.ico'
    ],

    'include_msvcr': True,
}



# GERADOR
setup(

    name = "Unicorn Mazer",
    version = "8.0",
    author = "Gustavo Pimenta",
    description='A game by Gustavo Pimenta [gustavopimenta.gp@gmail.com]',
    options = {"build_exe":build_exe_options, "build_msi":build_msi_options},
    executables=[

            Executable(

                'Unicorn Mazer Code.pyw',
                icon='icon.ico',
                base = 'Win32GUI',
                # shortcutName="Unicorn Mazer",
                # shortcutDir="DesktopFolder"

            )
    ]

)
